{{- if .Values.config.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rsyslog-receiver.fullname" . }}
  labels:
    {{- include "rsyslog-receiver.labels" . | nindent 4 }}
data:
  rsyslog.conf: |
    {{- tpl (.Files.Get "files/rsyslog.conf") . | nindent 4 }}
{{- end }}
