apiVersion: v1
kind: Service
metadata:
  name: {{ include "rsyslog-receiver.fullname" . }}
  labels:
    {{- include "rsyslog-receiver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: syslog-udp
      port: {{ .Values.service.port }}
      targetPort: syslog-udp
      protocol: UDP
    - name: syslog-tcp
      port: {{ .Values.service.port }}
      targetPort: syslog-tcp
      protocol: TCP
  selector:
    {{- include "rsyslog-receiver.selectorLabels" . | nindent 4 }}
