{{- if .Values.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "CHARTNAME.fullname" . }}
  labels:
    {{- include "CHARTNAME.labels" . | nindent 4 }}
data: {}
  # ここにアプリケーション設定データを追加する
  # config.yaml: |
  #   key: value
{{- end }}
