# values-dev.yaml - 開発環境オーバーライド
replicaCount: 1

image:
  repository: "docker.io/rsyslog/syslog_appliance_alpine"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

service:
  type: ClusterIP
  port: 514
  containerPort: 1514
  portName: "syslog-udp"
  protocol: UDP
