global(
  workDirectory="/var/lib/rsyslog"
)

module(load="imudp")
module(load="imtcp")

input(type="imudp" port="{{ .Values.syslog.port }}" ruleset="rfc5424check")
input(type="imtcp" port="{{ .Values.syslog.port }}" ruleset="rfc5424check")

ruleset(name="rfc5424check") {
    if ($protocol-version == "1") then {
        action(
            type="omfwd"
            target="{{ .Values.forwarder.target }}"
            port="{{ .Values.forwarder.port }}"
            protocol="tcp"
            template="RSYSLOG_SyslogProtocol23Format"
        )
    } else {
        stop
    }
}
