apiVersion: apps/v1
kind: Deployment
metadata:
  name: com-notifier-stub
  namespace: gems-ip
  labels:
    {{- include "com-notifier-stub.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "com-notifier-stub.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "com-notifier-stub.labels" . | nindent 8 }}
    spec:
      securityContext:
        fsGroup: 65534
      containers:
        - name: stub
          image: {{ include "com-notifier-stub.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 65534
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
