apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "CHARTNAME.fullname" . }}
  labels:
    {{- include "CHARTNAME.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  {{- with .Values.timeZone }}
  timeZone: {{ . | quote }}
  {{- end }}
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  {{- with .Values.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ . }}
  {{- end }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  suspend: {{ .Values.suspend }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.backoffLimit }}
      {{- with .Values.activeDeadlineSeconds }}
      activeDeadlineSeconds: {{ . }}
      {{- end }}
      {{- with .Values.ttlSecondsAfterFinished }}
      ttlSecondsAfterFinished: {{ . }}
      {{- end }}
      completions: {{ .Values.completions }}
      parallelism: {{ .Values.parallelism }}
      template:
        metadata:
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          labels:
            {{- include "CHARTNAME.labels" . | nindent 12 }}
            {{- with .Values.podLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          serviceAccountName: {{ include "CHARTNAME.serviceAccountName" . }}
          automountServiceAccountToken: {{ .Values.serviceAccount.automountToken }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          restartPolicy: {{ .Values.restartPolicy }}
          {{- with .Values.initContainers }}
          initContainers:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
          containers:
            - name: {{ .Chart.Name }}
              securityContext:
                {{- toYaml .Values.containerSecurityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}@{{ .Values.image.digest }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
              {{- with .Values.extraEnv }}
              env:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.extraEnvFrom }}
              envFrom:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              volumeMounts:
                - name: tmp
                  mountPath: /tmp
                {{- with .Values.extraVolumeMounts }}
                {{- toYaml . | nindent 16 }}
                {{- end }}
          volumes:
            - name: tmp
              emptyDir: {}
            {{- with .Values.extraVolumes }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.topologySpreadConstraints }}
          topologySpreadConstraints:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.priorityClassName }}
          priorityClassName: {{ . }}
          {{- end }}
          dnsPolicy: {{ .Values.dnsPolicy }}
          {{- with .Values.dnsConfig }}
          dnsConfig:
            {{- toYaml . | nindent 12 }}
          {{- end }}
